male(peter).
male(simon).
male(zakayo).
female(jane).
female(prisca).
female(mary).
female(ann).
male(pablo).
female(denver).
male(john).
parent(peter,john).
parent(simon,peter).
parent(jane,peter).
parent(mary,simon).
parent(john,denver).
parent(jane,prisca).
parent(jane,pablo).
parent(jane,ann).
grandchild(D,R):-parent(R,Y),parent(Y,D).
sister(A,B):-parent(C,A),parent(C,B),female(A),A\=B.
father(Q,U):-parent(Q,U),male(Q).
